#!/bin/bash -l

# Bash profile
export BASH_PROFILE="/Users/tmenninger/.bash_profile"

# Make sure scripts are up to date
(cd ${SCRIPTPATH}/.. && git pull 2&>1 /dev/null)

# NH2017 stuff
source ${SCRIPTPATH}/shared/ghs.sh

# SVN related tools
source ${SCRIPTPATH}/shared/svn.sh

# Common tools
source ${SCRIPTPATH}/shared/tools.sh

# Copy vim bundles to accessible directory
source ${SCRIPTPATH}/shared/vim_bundles.sh

