#!/bin/bash -l

SCRIPTPATH="/home/tmenninger/scripts/profiles"

# Bash profile
export BASH_PROFILE="/home/tmenninger/.bashrc"

# Make sure scripts are up to date
(cd ${SCRIPTPATH}/.. && git pull &>/dev/null)

# GHS tool stuff but for at home. Must be before ghs_tools, as it sets
# environment variables
source ${SCRIPTPATH}/shared/ghs.sh

# SVN related tools
source ${SCRIPTPATH}/shared/svn.sh

# Common tools
source ${SCRIPTPATH}/shared/tools.sh

# Gaming stuff
source ${SCRIPTPATH}/shared/n64.sh
source ${SCRIPTPATH}/shared/ps2.sh

# Copy vim bundles to accessible directory
source ${SCRIPTPATH}/shared/vim_bundles.sh

