#!/bin/bash -l

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

SCRIPTS_PATH="${HOME}/scripts/tmenninger"

# Bash profile
export BASH_PROFILE="${HOME}/.bashrc"

# Make sure scripts are up to date
(cd ${SCRIPTS_PATH} && git pull &>/dev/null)

# Pure Storage stuff
source ${SCRIPTS_PATH}/profiles/shared/pure.sh

# Common tools
source ${SCRIPTS_PATH}/profiles/shared/tools.sh

ssh-add /Users/tmenninger/.ssh/id_pure_root

# https://purestorage.atlassian.net/wiki/spaces/GHE/pages/4081615105/Migrate+from+SSH+Keys+or+OAuth+to+SSH+Certificates
export VAULT_ADDR=https://vault.purestorage.com
export PURELOGIN_VAULT=1
export PURELOGIN_VAULT_STORE_TOKEN=1
export PURELOGIN_OVERWRITE_VAULT_CERT=1
