#!/bin/bash -l

SCRIPTPATH="/home/willow/scripts/profiles"

# NH2017 directory
export NH2017="/t/toolsvc/trunk/users/nh2017"

# Source bash profile
export BASH_PROFILE="/opt/home/tmenninger/.bashrc"

# Make sure scripts are up to date
(cd ${SCRIPTPATH}/.. && git pull &>/dev/null)

# Stuff when we are on GHS network
source ${SCRIPTPATH}/shared/ghs.sh
GHSCOMP_DIR="/t/toolsvc/trunk/linux64-comp"

# SVN related tools
source ${SCRIPTPATH}/shared/svn.sh

# Common tools
source ${SCRIPTPATH}/shared/tools.sh

# Copy vim bundles to accessible directory
source ${SCRIPTPATH}/shared/vim_bundles.sh

