#!/bin/bash -l

SCRIPTPATH="/home/willow/scripts/profiles"

# NH2017 directory
export NH2017="/tools/users/nh2017"

# Source bash profile
export BASH_PROFILE="/tools/users/.bashrc"

# Stuff when we are on GHS network
source ${SCRIPTPATH}/shared/ghs_network.sh

# Stuff relating to GHS tool
source ${SCRIPTPATH}/shared/ghs_tools.sh
source ${SCRIPTPATH}/shared/ghs_given.sh

# Android stuff
source ${SCRIPTPATH}/shared/android.sh

# NH2017 stuff
source ${SCRIPTPATH}/shared/nh2017.sh

# SVN related tools
source ${SCRIPTPATH}/shared/svn.sh

# Standardize version control stuff
source ${SCRIPTPATH}/shared/vc.sh

# Common tools
source ${SCRIPTPATH}/shared/tools.sh


