#!/bin/bash -l

SCRIPTPATH="/home/willow/scripts/profiles"

# No Zonedin directory
export ZONEDIN=".; echo \"No zoned in\""

# NH2017 directory
export NH2017="/home/willow/nh2017"

# Bash profile
export BASH_PROFILE="/home/eng/users/tmenninger/.bashrc"

# Make sure scripts are up to date
(cd ${SCRIPTPATH}/.. && git pull 2&>1 /dev/null)

# Fix monitors
source ${SCRIPTPATH}/shared/workstation_monitors.sh

# Stuff when we are on GHS network
source ${SCRIPTPATH}/shared/ghs_network.sh

# Stuff relating to GHS tool
source ${SCRIPTPATH}/shared/ghs_tools.sh
source ${SCRIPTPATH}/shared/ghs_given.sh

# Android stuff
source ${SCRIPTPATH}/shared/android.sh

# NH2017 stuff
source ${SCRIPTPATH}/shared/nh2017.sh

# SVN related tools
source ${SCRIPTPATH}/shared/svn.sh

# Standardize version control stuff
source ${SCRIPTPATH}/shared/vc.sh

# Common tools
source ${SCRIPTPATH}/shared/tools.sh


