#!/bin/bash -l

SCRIPTPATH="/home/willow/scripts/profiles"

# Bash profile
export BASH_PROFILE="/home/eng/users/tmenninger/.bashrc"

# Video player paths
export GHS_VideoPlayerPath="/home/vulcan0/bigtmp/vidstory_tools/videoplayer"
export LD_LIBRARY_PATH="/home/vulcan0/bigtmp/vidstory_tools/libs"

# Video multi dsnap reader
alias multi_video="/home/vulcan0/bigtmp/trunk/linux64-ide/multi -GHSXHistoryVideo"

# Make sure scripts are up to date
(cd ${SCRIPTPATH}/.. && git pull &>/dev/null)

# Stuff when we are working for ghs
source ${SCRIPTPATH}/shared/ghs.sh

# SVN related tools
source ${SCRIPTPATH}/shared/svn.sh

# Common tools
source ${SCRIPTPATH}/shared/tools.sh

# Copy vim bundles to accessible directory
source ${SCRIPTPATH}/shared/vim_bundles.sh


